### ISSUE TITLE
Big Sur support

### ISSUE THREAD

**Issue by coatless** [rmacoslib/r-macos-rtools#42]
Hi, 
I got it opened!
But the installation failed. I am on macOS Big Sur 11.0.1.
I took a screen shot:

<img width="986" alt="Screen Shot 2020-11-27 at 11 12 46 AM" src="https://user-images.githubusercontent.com/39174724/100407236-cf8ea780-30a2-11eb-9415-973958ff6cc7.png">

_Originally posted by @paprika920 in https://github.com/rmacoslib/r-macos-rtools/issues/39#issuecomment-734625941_

**Comment by coatless** [comment]
@paprika920 everything should largely be setup. There are two notably exceptions:

1. Xcode Command Line Tools
2. An additional flag to address compilation errors on >= Xcode CLI 12.2

Xcode CLI is having odd issues with being downloaded on some machines. You may wish to directly download it from: 

https://developer.apple.com/download/more/

The compilation error that may occur when compiling code is given as:

```cpp
conftest.c:227:1: error: implicit declaration of function 'dgemm_' is
invalid in
  C99 [-Werror,-Wimplicit-function-declaration]
```

As noted by Prof. Ripley at: https://stat.ethz.ch/pipermail/r-sig-mac/2020-November/013789.html

This can be addressed by adding into `~/.R/Makevars`:

```bash
CFLAGS=-Wno-implicit-function-declaration
```

For more details, see the note in [Section 6.3.2 of R Administration and Installation Manual](https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#macOS-packages)

**Comment by egarpor** [comment]
Same issue here as @paprika920. I added to my `~/.R/Makevars`
```
$ cat Makevars
CFLAGS=-Wno-implicit-function-declaration
```
However, the installation continues to fail with the same error message. Any help is much appreciated. Using Big Sur 11.0.1 and R 4.0.3.

**Comment by LucaGiangregorio93** [comment]
I also have the same issue using R 4.0.3 and Big Sur 11.1. 
Anyone has solved the problem?

**Comment by thepoorv** [comment]
Same issue...installation failure with Big Sur...would really appreciate advice on how to solve this issue!

**Comment by egarpor** [comment]
FWIW, in my case, after reinstalling R, the Xcode Command Line Tools, and rebooting the computer, I was able to build packages again. I did not install r-macos-rtools.

**Comment by avocardio** [comment]
Same here... any updates?

**Comment by JohnMBeltran** [comment]
Seems like there is yet to be an update for the cpp  toolchain. I simply downgraded back to Catalina and it all works fine again.

**Comment by stefanocoretta** [comment]
`r-macos-rtools` does not yet support Big Sur. This is what I did that worked (after an Odyssey of trial and error).

Disclaimer: I started from a fresh install of Big Sur with no R, nor RStudio, nor Apple's Command Line Tools installed, so this might not work well if you have already an installation of those.

I installed Apple's Command Line Tools with:

```bash
xcode-select --install
```

I installed the gfortran compiler from here: https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/8.2. **NOTE**: I installed gfortran-8.2 for Mojave even though I am running Big Sur. R is compiled with that version of gfortran and I can't promise it would work with a later version, and very likely it does not.

I installed R-4.0.3 from CRAN: <https://cran.r-project.org/bin/macosx/>.

I installed RStudio with Homebrew, but you can just install it from <https://rstudio.com/products/rstudio/download/>. ~~**NOTE**: If you have Homebrew and you are using it, this is what might cause issues when you compile R packages from source **if you have installed `gcc`**. I think this is an issue with `$PATH` but I am not sure. Now I am running everything while having Homebrew **but not** the `gcc` formula. So I don't know whether things would work with that installed. When/if I will have to install `gcc`, I'll update this post.~~ UPDATE: I also installed the gcc formula with brew and things seem to be ok.

**Make sure you don't have a `Makevars file`** in `~/.R/`. If you do, move it somewhere else.

Now you should be able to compile packages from source. If you see red text when you install from source, but installation goes fine (meaning, the package is installed and can be loaded/attached and used), that red text is just warnings, which can be safely disregarded. If the package is not installed and you see ERROR somewhere in the text, then there is something wrong with the C++ toolchain, alas.

### RStan

If you are installing the C++ toolchain because you want to install RStan and brms, this is what worked for me (as of 2021-01-23).

I installed RStan from source with:

```r
install.packages("rstan", type = "source")
```

Again, if you see red text, it is just warnings, if the package gets installed and can be loaded.

See if RStan has been installed successfully.

```r
example(stan_model, package = "rstan", run.dontrun = TRUE)
```

If it compiles the model and starts sampling, all is good.

Now you can install brms.

```r
install.packages("brms")
```

### Extra

I recommend using a `site-library`, so that something goes wrong, you can just delete everything in it to get back to a "fresh-install" of R (the base packages are retained, because they reside in `library`).

You probably have to create the `site-library` and the easies way is to do that from the terminal:

```bash
mkdir /Library/Frameworks/R.framework/Versions/4.0/Resources/site-library
```

This will become the default library when you install packages in RStudio. To check that it worked, do in R:

```r
.libPaths()
> [1] "/Library/Frameworks/R.framework/Versions/4.0/Resources/site-library"
> [2] "/Library/Frameworks/R.framework/Versions/4.0/Resources/library" 
```

**Comment by yina-quique** [comment]
Hi everyone, any updates? 
I am working on apple M1. R version 4.0 and I have the same installation error. Any recommendations? 


<img width="618" alt="Screen Shot 2021-02-06 at 10 05 37 PM" src="https://user-images.githubusercontent.com/47012923/107136489-3ca39200-68c9-11eb-827b-da50fdd0e7c6.png">

**Comment by stefanocoretta** [comment]
> Hi everyone, any updates?
> I am working on apple M1. R version 4.0 and I have the same installation error. Any recommendations?
> 
> <img alt="Screen Shot 2021-02-06 at 10 05 37 PM" width="618" src="https://user-images.githubusercontent.com/47012923/107136489-3ca39200-68c9-11eb-827b-da50fdd0e7c6.png">

See my comment above. :)

**Comment by yina-quique** [comment]
Hi, thank you for answering. Although I have no experience with the command line, I successfully installed `xcode-select --install` from it. Then, I tried to install "the gfortran compiler", but I couldn't find it in the link that you provided. So, I'm stuck again. (Just in case, I am also trying to install it so I can install rStan). Any help is appreciated!

**Comment by stefanocoretta** [comment]
Updated the comment with a direct link to gfortran 8.2. :)

**Comment by coatless** [comment]
Folks, I'm locking this thread as it's now off-topic.

The installer itself is just a GUI for a bash script that recreates the step-by-step workflow here: 

https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/
